package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildSteps.dotnetBuild
import jetbrains.buildServer.configs.kotlin.buildSteps.nunitConsole
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'NUnitNew_BuildNUnit'
in the project with id = 'NUnitNew', and delete the patch script.
*/
create(RelativeId("NUnitNew"), BuildType({
    id("NUnitNew_BuildNUnit")
    name = "BuildNUnit"

    vcs {
        root(RelativeId("NUnitNew_HttpsGithubComChubatovaTigerDotNetTestsSamplesRefsHeadsMain"))
    }

    steps {
        dotnetBuild {
            id = "dotnet"
            projects = "TestProject2/TestProject2.csproj"
            outputDir = "out"
        }
        script {
            id = "simpleRunner"
            scriptContent = "dir out"
            param("org.jfrog.artifactory.selectedDeployableServer.useSpecs", "false")
            param("org.jfrog.artifactory.selectedDeployableServer.uploadSpecSource", "Job configuration")
            param("org.jfrog.artifactory.selectedDeployableServer.downloadSpecSource", "Job configuration")
        }
        nunitConsole {
            id = "nunit_console"
            nunitPath = "%teamcity.tool.NUnit.Console.DEFAULT%"
            includeTests = """out\TestProject2.dll"""
        }
    }
}))

