package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildSteps.dotnetBuild
import jetbrains.buildServer.configs.kotlin.buildSteps.nunitConsole
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'NUnitNew_97335'
in the project with id = 'NUnitNew', and delete the patch script.
*/
create(RelativeId("NUnitNew"), BuildType({
    id("NUnitNew_97335")
    name = "97335"

    vcs {
        root(RelativeId("NUnitNew_HttpsGithubComChubatovaTiger97335refsHeadsMaster"))
    }

    steps {
        dotnetBuild {
            id = "dotnet"
            enabled = false
            projects = "**/**.csproj"
            outputDir = "out1"
            sdk = "6"
        }
        dotnetBuild {
            name = "New build step (1)"
            id = "dotnet_2"
            enabled = false
            projects = "TestProject/TestProject.csproj"
            outputDir = "out2"
            sdk = "6"
        }
        dotnetBuild {
            name = "New build step"
            id = "dotnet_1"
            enabled = false
            projects = "TestProject/TestProject.csproj"
            outputDir = "purout"
            sdk = "6"
        }
        nunitConsole {
            id = "nunit_console"
            nunitPath = "%teamcity.tool.NUnit.Console.DEFAULT%"
            includeTests = """**bin\Release\net472\TestProject*.dll"""
            excludeCategories = """
                BuildOnBuildServer
                Performance
            """.trimIndent()
            reduceTestFeedback = true
            args = "--timeout=60000"
        }
    }
}))

