package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'NUnitNew_HttpsGithubComChubatovaTiger97335refsHeadsMaster'
in the project with id = 'NUnitNew', and delete the patch script.
*/
create(RelativeId("NUnitNew"), GitVcsRoot({
    id("NUnitNew_HttpsGithubComChubatovaTiger97335refsHeadsMaster")
    name = "https://github.com/ChubatovaTiger/97335#refs/heads/master"
    url = "https://github.com/ChubatovaTiger/97335"
    branch = "refs/heads/master"
    branchSpec = "refs/heads/(*)"
    checkoutSubmodules = GitVcsRoot.CheckoutSubmodules.IGNORE
    checkoutPolicy = GitVcsRoot.AgentCheckoutPolicy.NO_MIRRORS
    authMethod = password {
        password = "credentialsJSON:b52775aa-53a6-4ee8-8b8f-79503fa059b2"
    }
}))

